#
# SITE SETTINGS
#

# references for updates
# https://iconsvg.xyz
# https://feathericons.com/

# site information

title: Jean-Joseph Minviel
description: > # this means to ignore newlines until the next tag
  Researcher<br/>
  INRAE, ECOSOCIO<br/>
  UMR Herbivores
author: Jean-Joseph Minviel
baseurl: ""

url: "http://jeanjosephminviel.github.io"
blog_dir: /blog
permalink: /blog/posts/:year/:month/:day/:title/ # prefixed style
category_dir: /blog/categories/
category_title_prefix: "category: "

# author information

picture: images/PCE.jpg
email: jean-joseph.minviel@inrae.fr

networks:
  twitter:
    url: https://twitter.com/
    username: jjminviel
  github:
    url: https://github.com/
    username: jjminviel
  dblp:
    url: http://www.informatik.uni-trier.de/~ley/pers/hd/
    username: p/Minviel:Jean


# apparence of posts

# apparence of buttons

link_btn_size: btn-xs
link_btn_color: btn-primary
publications_btn_size: btn-xs
publications_btn_color: btn-default
publications_btn_textcolor: text-primary

# alerts

alerts:
  no-javascript:
    danger: true
    warning: true
    information:  true

# bibliography

kind:
  label: pp_kind # label used in .bib files to denote the kind (international/national) of references
  separate:  # should international/national references be separated: (true | false)
    article: true
    inbook: false
    inproceedings: true

scholar:
  style: _bibliography/mystyle.csl
  locale: en
  sort_by: year, pp_rank
  order: descending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: false
  bibtex_skip_fields: [pp_shortbooktitle, pp_rank, pp_kind]
  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details
  query: "@*"

# other settings

exclude:  ['Gemfile*', '*.sh', 'update_site.sh']

plugins: ['jekyll/scholar']

markdown: kramdown
highlighter: rouge

kramdown:
     # input: GFM
     syntax_highlighter: rouge
